{% set name = "mahotas" %}
{% set version = "1.4.1" %}
{% set sha256 = "40b2ee831b66247541706b28db0d4b187d051d5fda926a0c43912d27b3be50c0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - numpy x.x

  run:
    - python
    - numpy x.x

test:
  requires:
    - nose
    - scipy
    - pillow

  imports:
    - mahotas

  commands:
    - mahotas-features.py --help

about:
  home: http://luispedro.org/software/mahotas/
  license: MIT
  license_family: MIT
  license_file: COPYING

  summary: "Mahotas: Computer Vision Library"
  description: |
    Mahotas is a library of fast computer vision algorithms
    (all implemented in C++) operating over numpy arrays.

  doc_url: http://mahotas.rtfd.io/
  dev_url: https://github.com/luispedro/mahotas

extra:
  recipe-maintainers:
    - jakirkham
