{% set name = "mahotas" %}
{% set version = "1.4.3" %}
{% set sha256 = "e113fb73f1f717f1a9124b41496b030628efb72a23b0150a42ecb18b08b030c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    # Adds a patch to get the result of running the test suite.
    # Please see PR submitted upstream for more details.
    #
    # https://github.com/luispedro/mahotas/pull/81
    #
    - PR_81.diff

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - numpy x.x

  run:
    - python
    - numpy x.x

test:
  requires:
    - nose
    - scipy
    - pillow

  imports:
    - mahotas

  commands:
    - mahotas-features.py --help

about:
  home: http://luispedro.org/software/mahotas/
  license: MIT
  license_family: MIT
  license_file: COPYING

  summary: "Mahotas: Computer Vision Library"
  description: |
    Mahotas is a library of fast computer vision algorithms
    (all implemented in C++) operating over numpy arrays.

  doc_url: http://mahotas.rtfd.io/
  dev_url: https://github.com/luispedro/mahotas

extra:
  recipe-maintainers:
    - jakirkham
