appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: BVK3Pr3rt71MrQDDDDOr0cAO/P1MCtHhyVtP8emGviGV90sGa/rKTRvSNTBrRKmb+cQji0Er/T5VSd84sEDVpakHuooXgwD0i81FXzbpbJS96gRSzRIOmtQSuiSL/8J07NdDboFAhPMLNz9trAaUbqUoDpPBQt3GG3ldS7AUC0JukUIj4pxTKrTiHQ7Vi3gNaCmHfTwH++rGN2seVQP3/2tAwWGSlNx2AaSBEoUdDncE+VzQt6+25uC1bkIDfUafdv/8kzelGltcmOvV/nJF09rFSinjnyjY8HESjTdCm+X395b4YmHgsjW7Pa+3uZP79H5jBOtXmGRHJzEcBS0LEY/L9J3SO9GGUUf1HAJcbdj/qieizSBI73FTp4zHU5n9ZRrPDoWazi8e7Ab7nL+tE68Dwa0vIAXRDZJOEQC9xDe8IZY4MaG8rThZgqeX9GEzf0DHoSUph2AScB69U42auMhLeVFKHINSTVkdY8t3yGBDpA9wjtHZpdtv/ihlb6V+W4aIkyCYZKs3zQV9UxP1ELiVyyD//XatfYELEZ1ba32hsyAdpfnyCAL1II23Uv0t75arhRoz+6ocCvfm0bLcxFRFHdHI9nKZ9T9zp6C55EQaqsTKdc3an3s7iqH3UPb5p/HZNhGBYqPHPZAcDxEgrYcOGibNmC3l32aLVTGITeY=}
provider:
  win: azure
conda_forge_output_validation: true
